AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app with API Gateway integration.

Globals:
  Function:
    Timeout: 15  # Default timeout for all Lambda functions
    MemorySize: 128  # Default memory allocation for all Lambda functions

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function  # Defines a Lambda function
    Properties:
      CodeUri: ./  # Directory containing your Lambda function code
      Handler: handlers.listAllTables.lambda_handler  # Function entry point
      Runtime: python3.11  # Runtime environment
      Architectures:
        - x86_64  # Architecture
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello  # Define the API endpoint
            Method: GET   # HTTP method
            Cors:  # CORS configuration
              AllowMethods: "'GET'"
              AllowHeaders: "'Content-Type'"
              AllowOrigins: "'*'"

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

